In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout,Activation,BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint   
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns 
import keras
from keras.utils import np_utils
from tensorflow.keras.datasets import mnist

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
print(len(X_train))
print(len(X_test))

60000
10000


In [ ]:
X_train = X_train.astype('float32')/255 #Scaling the data
X_test = X_test.astype('float32')/255 

print('X_train shape:', X_train.shape)
print(X_train.shape[0], '=train samples')
print(X_test.shape[0], '=test samples')

X_train shape: (60000, 28, 28)
60000 =train samples
10000 =test samples


In [ ]:
num_classes = 10 
# print first ten (integer-valued) training labels
print('Integer-valued labels:')
print(y_train[:10])

# one-hot encode the labels
# convert class vectors to binary class matrices
y_train = np_utils.to_categorical(y_train, num_classes)
y_test = np_utils.to_categorical(y_test, num_classes)

# print first ten (one-hot) training labels
print('One-hot labels:')
print(y_train[:10])

Integer-valued labels:
[5 0 4 1 9 2 1 3 1 4]
One-hot labels:
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
img_rows, img_cols = 28, 28

X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

print('input_shape: ', input_shape)
print('x_train shape:', X_train.shape)

input_shape:  (28, 28, 1)
x_train shape: (60000, 28, 28, 1)


In [ ]:
model = Sequential()
model.add(Conv2D(filters=10,kernel_size=(3,3), activation='relu', input_shape=(28,28,1))) #26

model.add(Conv2D(filters=10,kernel_size=(3,3), activation='relu'))  #24         
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(filters=10,kernel_size=(3,3), activation='relu')) # 22
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(MaxPooling2D(pool_size=(2, 2))) #11

model.add(Conv2D(filters=16,kernel_size=(3,3), activation='relu')) # 9
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(filters=10,kernel_size=(1,1), activation='relu')) # 9
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(filters=10,kernel_size=(3,3), activation='relu')) #7      
model.add(BatchNormalization())
model.add(Dropout(0.1))

 
model.add(Conv2D(filters=10,kernel_size=(3,3), activation='relu')) #5       
model.add(BatchNormalization())
model.add(Dropout(0.1))


model.add(Conv2D(filters=10,kernel_size=(5,5))) #1 

model.add(Flatten())
model.add(Activation('softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_15 (Conv2D)           (None, 26, 26, 10)        100       
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 24, 24, 10)        910       
_________________________________________________________________
batch_normalization_11 (Batc (None, 24, 24, 10)        40        
_________________________________________________________________
dropout_11 (Dropout)         (None, 24, 24, 10)        0         
_________________________________________________________________
conv2d_17 (Conv2D)           (None, 22, 22, 10)        910       
_________________________________________________________________
batch_normalization_12 (Batc (None, 22, 22, 10)        40        
_________________________________________________________________
dropout_12 (Dropout)         (None, 22, 22, 10)       

In [ ]:
def scheduler(epoch, lr):
  return round(0.003 * 1/(1 + 0.319 * epoch), 10)
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=0.003), metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=128, epochs=30, verbose=1, validation_data=(X_test, y_test),
          callbacks=[tf.keras.callbacks.LearningRateScheduler(scheduler, verbose=1)])

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


Epoch 1/30

Epoch 00001: LearningRateScheduler reducing learning rate to 0.003.
469/469 [==============================] - 5s 8ms/step - loss: 0.2271 - accuracy: 0.9286 - val_loss: 0.1337 - val_accuracy: 0.9596
Epoch 2/30

Epoch 00002: LearningRateScheduler reducing learning rate to 0.0022744503.
469/469 [==============================] - 3s 7ms/step - loss: 0.0773 - accuracy: 0.9761 - val_loss: 0.0508 - val_accuracy: 0.9824
Epoch 3/30

Epoch 00003: LearningRateScheduler reducing learning rate to 0.0018315018.
469/469 [==============================] - 4s 8ms/step - loss: 0.0606 - accuracy: 0.9815 - val_loss: 0.0348 - val_accuracy: 0.9878
Epoch 4/30

Epoch 00004: LearningRateScheduler reducing learning rate to 0.0015329586.
469/469 [==============================] - 3s 7ms/step - loss: 0.0527 - accuracy: 0.9836 - val_loss: 0.0355 - val_accuracy: 0.9882
Epoch 5/30

Epoch 00005: LearningRateScheduler reducing learning rate to 0.0013181019.
469/469 [==============================] - 3s 7m

Here i run for 30 epochs but in 25 epcohs i got validation accuracy as 99.40%.